backend:
  name: git-gateway

media_folder: "src/assets/images"
public_folder: "src/assets/images"

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/news
    label: "news" # Used in the UI
    folder: "src/content/news" # The path to the folder where the documents are stored
    create: true 
    edit: true 
    delete: true 
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
