backend:
  name: git-gateway
  repo: cmattless/tennis-test
  branch: main

media_folder: "src/assets/images"
public_folder: "src/assets/images"

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/news
    label: "news" # Used in the UI
    folder: "src/pages/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "news" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
