backend:
  name: git-gateway
  repo: cmattless/tennis-test
  branch: main

media_folder: "src/assets/images"
public_folder: "src/assets/images"

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/news
    label: "News" # Used in the UI
    folder: "src/content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    edit: true # Allow users to edit existing documents in this collection
    delete: true # Allow users to delete documents in this collection
    update: true # Allow users to update existing documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "$/layouts/news.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Image Alt Text", name: "alt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "policies"
    label: "Policies"
    folder: "src/content/policies"
    create: true
    edit: true
    delete: true
    update: true
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "$/layouts/policies.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
    
  - name: "committee"
    label: "Committee"
    folder: "src/content/committee"
    create: true
    edit: true
    delete: true
    update: true
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "$/layouts/committee.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "photos"
    label: "Photos"
    folder: "content/photos"
    create: true
    slug: "{{slug}}"
    fields:
      - { labelL: "Layout", name: "layout", widget: "hidden", default: "$/layouts/photos.astro" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
