backend:
  name: git-gateway
  repo: cmattless/tennis-test
  branch: main


media_folder: "src/assets/images"
public_folder: "src/assets/images"

collections:
  - name: "news"
    label: "News"
    folder: "src/content/news"
    create: true
    edit: true
    delete: true
    update: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Image Alt Text", name: "alt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "policies"
    label: "Policies"
    folder: "src/content/policies"
    create: true
    edit: true
    delete: true
    update: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "committee"
    label: "Committee"
    folder: "src/content/committee"
    create: true
    edit: true
    delete: true
    update: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "photos"
    label: "Photos"
    folder: "src/content/photos"
    create: true
    edit: true
    delete: true
    update: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "alt", name: "alt", widget: "string", required: false }
      - {
          label: "Description",
          name: "description",
          widget: "markdown",
          required: false,
        }
      - { label: "Date", name: "date", widget: "datetime" }
      # Here is the multi-image upload
      - label: "Images"
        name: "images"
        widget: "list"
        summary: "{{fields.image}}"  # show image path in list summary
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt text", name: "alt", widget: "string", required: false }
